server:
  port: 3344

spring:
  application:
    name: cloud-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/lulu4pix/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
          username: 914104723@qq.com
          password: Aa123567.
      label: master
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#rabbitmq相关配置，暴露bus刷新配置端点
management:
  endpoints:  #暴露bus配置的端点
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/     #单机版


